version: 2
jobs:
  build:
    docker:
      # Use node 10 for the monorepo docs sake (temporarily)
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint

      - run: GATSBY_CPU_COUNT=1 yarn build
      - run: yarn build-storybook
      - run: yarn chromatic --storybook-build-dir storybook-static --exit-zero-on-changes
